version: '3'
services:
  xhgui:
    image: edyan/xhgui:php7.2
    container_name: xhgui
    restart: unless-stopped
    volumes:
      - ./conf/xhgui-config.php:/usr/local/src/xhgui/config/config.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xhgui-xhgui.entryPoints=web,websecure"
      - "traefik.http.routers.xhgui-xhgui.rule=Host(`xhgui.deckle.local`)"
      - "traefik.http.services.xhgui-xhgui.loadbalancer.server.port=80"

networks:
   default:
     external:
       name: deckle
